### ISSUE TITLE
!findMatches doesn't work when there are multiple users with the same name on the server

### ISSUE THREAD

**Issue by ammuench** [ammuench/ld2l-discord-bot#8]
Trying to run a !findMatches for MnQuake currently returns a "user not registered" error.  This is due to multiple users on the server all being named MnQuake.

Not sure what the best solution is, simply returning options may work? (Like "there are 4 MnQuakes, please respond with !findMatches MnQuake 3")

Otherwise, this is reason to build a findMatches variant to show a list of upcoming matches maybe?

**Comment by hiemanshu** [comment]
If this is only being used for the casters, I'd rather do a findMatch by day or date, or even a time period maybe. So have !findMatches Thursday, or !findMatches returns matches for the next week. !findmatches old returns old matches and !findmatches all returns everything, !findmatches upcoming returns all new matches.

**Comment by ammuench** [comment]
Yeah, in retrospect, searching by day makes more sense. I think using
actual date as a parameter (and maybe timezone too) would work best.
Default to matches from today on the GMT calendar.

I think showing all future matches, or even all matches for the next week
is gonna be too much data to read through in a discord message. This week
has been a little sparse with scheduling, but next week should be our first
full week where everyone needs to use the calendar.

**Comment by ammuench** [comment]
New issues here:
https://github.com/ammuench/ld2l-discord-bot/issues/9
